server:
#  port: 3306
  port: 8081

spring:
  application:
    name: housing
  datasource:
    url: jdbc:mysql://localhost/bootcamp2025_s1
    username: root
    password: ""
  jpa:
    hibernate:
      ddl-auto: update